// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmbwAxDLYcZ6UU7OqE2-GrIjQxUvTwbQY',
    appId: '1:323774713076:web:97df75eeecd4c006a5e2a1',
    messagingSenderId: '323774713076',
    projectId: 'healthcompanion-7fa3a',
    authDomain: 'healthcompanion-7fa3a.firebaseapp.com',
    storageBucket: 'healthcompanion-7fa3a.appspot.com',
    measurementId: 'G-CBCLTJ30Y2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZRb_exqfPFqNZsqHctM9CrNDRqmBkw_w',
    appId: '1:323774713076:android:7cf594bac56a6085a5e2a1',
    messagingSenderId: '323774713076',
    projectId: 'healthcompanion-7fa3a',
    storageBucket: 'healthcompanion-7fa3a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC5aZydv5jcL1-lWnoGTGNg8Pg01Qyu3xc',
    appId: '1:323774713076:ios:24cb2bac5fe6fe49a5e2a1',
    messagingSenderId: '323774713076',
    projectId: 'healthcompanion-7fa3a',
    storageBucket: 'healthcompanion-7fa3a.appspot.com',
    iosClientId: '323774713076-0jm3m0iem2hbiv78jmigp21a50n1vcl5.apps.googleusercontent.com',
    iosBundleId: 'com.companion.healthCompanion',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC5aZydv5jcL1-lWnoGTGNg8Pg01Qyu3xc',
    appId: '1:323774713076:ios:24cb2bac5fe6fe49a5e2a1',
    messagingSenderId: '323774713076',
    projectId: 'healthcompanion-7fa3a',
    storageBucket: 'healthcompanion-7fa3a.appspot.com',
    iosClientId: '323774713076-0jm3m0iem2hbiv78jmigp21a50n1vcl5.apps.googleusercontent.com',
    iosBundleId: 'com.companion.healthCompanion',
  );
}
